name: RedMonkeyPvPStats
version: '${version}'
main: me.j0keer.redmonkeypvpstats.Main
api-version: 1.19
depend:
  - PlaceholderAPI
description: A statistics plugin with hook into PlaceholderAPI with per-world support.
